name: Rolinsf前端展示

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.0.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: 安装依赖
        working-directory: frontend
        run: npm install

      - name: 构建项目
        working-directory: frontend
        run: npm run build
        # env:
          # VUE_APP_API_BASE_URL: ${{ secrets.VUE_APP_API_BASE_URL }}

      - name: 暂存构建产物
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./frontend/dist

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }} 
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: 'deploy: 自动部署 ${{ github.sha }}'
    